// Generated by tools/gen.py; edit that, not this.
//
// Gather, Scatter and ScatterAdd: moving elements by an index buffer.
// An index out of range traps, as every span access does.
import "gpu"

func _gatherFloat32(_ src: gpu.Span<float32>, _ indices: gpu.Span<uint32>, _ out: gpu.MutableSpan<float32>) kernel {
    let i = gpu.Index.x
    if i < indices.count {
        out[i] = src[int(indices[i])]
    }
}

func _scatterFloat32(_ src: gpu.Span<float32>, _ indices: gpu.Span<uint32>, _ dst: gpu.MutableSpan<float32>) kernel {
    let i = gpu.Index.x
    if i < indices.count {
        dst[int(indices[i])] = src[i]
    }
}

func _scatterAddFloat32(_ src: gpu.Span<float32>, _ indices: gpu.Span<uint32>, _ dst: gpu.MutableSpan<float32>) kernel {
    let i = gpu.Index.x
    if i < indices.count {
        _ = gpu.Atomic.Add(dst.Address(int(indices[i])), src[i])
    }
}

/// Gather is src at each of indices: out[i] = src[indices[i]].
public func Gather(_ src: gpu.Buffer<float32>, _ indices: gpu.Buffer<uint32>) async throws -> gpu.Buffer<float32> {
    let out = try await src.Device.CreateBuffer(of: float32.self, count: indices.count)
    if indices.count > 0 {
        try await _gatherFloat32.Launch(src, indices, out, over: indices.count)
    }
    return out
}

/// Scatter writes each element of src to dst at its index: dst[indices[i]]
/// = src[i]. Where two indices are the same, which write lands is not
/// defined.
public func Scatter(_ src: gpu.Buffer<float32>, _ indices: gpu.Buffer<uint32>, into dst: gpu.Buffer<float32>) async throws {
    if indices.count > 0 {
        try await _scatterFloat32.Launch(src, indices, dst, over: indices.count)
    }
}

/// ScatterAdd adds each element of src into dst at its index, atomically:
/// dst[indices[i]] += src[i]. An integer sum is exact whatever the order; a
/// float32 one is not deterministic, as the order of the additions is not.
public func ScatterAdd(_ src: gpu.Buffer<float32>, _ indices: gpu.Buffer<uint32>, into dst: gpu.Buffer<float32>) async throws {
    if indices.count > 0 {
        try await _scatterAddFloat32.Launch(src, indices, dst, over: indices.count)
    }
}

func _gatherInt32(_ src: gpu.Span<int32>, _ indices: gpu.Span<uint32>, _ out: gpu.MutableSpan<int32>) kernel {
    let i = gpu.Index.x
    if i < indices.count {
        out[i] = src[int(indices[i])]
    }
}

func _scatterInt32(_ src: gpu.Span<int32>, _ indices: gpu.Span<uint32>, _ dst: gpu.MutableSpan<int32>) kernel {
    let i = gpu.Index.x
    if i < indices.count {
        dst[int(indices[i])] = src[i]
    }
}

func _scatterAddInt32(_ src: gpu.Span<int32>, _ indices: gpu.Span<uint32>, _ dst: gpu.MutableSpan<int32>) kernel {
    let i = gpu.Index.x
    if i < indices.count {
        _ = gpu.Atomic.Add(dst.Address(int(indices[i])), src[i])
    }
}

/// Gather is src at each of indices: out[i] = src[indices[i]].
public func Gather(_ src: gpu.Buffer<int32>, _ indices: gpu.Buffer<uint32>) async throws -> gpu.Buffer<int32> {
    let out = try await src.Device.CreateBuffer(of: int32.self, count: indices.count)
    if indices.count > 0 {
        try await _gatherInt32.Launch(src, indices, out, over: indices.count)
    }
    return out
}

/// Scatter writes each element of src to dst at its index: dst[indices[i]]
/// = src[i]. Where two indices are the same, which write lands is not
/// defined.
public func Scatter(_ src: gpu.Buffer<int32>, _ indices: gpu.Buffer<uint32>, into dst: gpu.Buffer<int32>) async throws {
    if indices.count > 0 {
        try await _scatterInt32.Launch(src, indices, dst, over: indices.count)
    }
}

/// ScatterAdd adds each element of src into dst at its index, atomically:
/// dst[indices[i]] += src[i]. An integer sum is exact whatever the order; a
/// float32 one is not deterministic, as the order of the additions is not.
public func ScatterAdd(_ src: gpu.Buffer<int32>, _ indices: gpu.Buffer<uint32>, into dst: gpu.Buffer<int32>) async throws {
    if indices.count > 0 {
        try await _scatterAddInt32.Launch(src, indices, dst, over: indices.count)
    }
}

func _gatherUint32(_ src: gpu.Span<uint32>, _ indices: gpu.Span<uint32>, _ out: gpu.MutableSpan<uint32>) kernel {
    let i = gpu.Index.x
    if i < indices.count {
        out[i] = src[int(indices[i])]
    }
}

func _scatterUint32(_ src: gpu.Span<uint32>, _ indices: gpu.Span<uint32>, _ dst: gpu.MutableSpan<uint32>) kernel {
    let i = gpu.Index.x
    if i < indices.count {
        dst[int(indices[i])] = src[i]
    }
}

func _scatterAddUint32(_ src: gpu.Span<uint32>, _ indices: gpu.Span<uint32>, _ dst: gpu.MutableSpan<uint32>) kernel {
    let i = gpu.Index.x
    if i < indices.count {
        _ = gpu.Atomic.Add(dst.Address(int(indices[i])), src[i])
    }
}

/// Gather is src at each of indices: out[i] = src[indices[i]].
public func Gather(_ src: gpu.Buffer<uint32>, _ indices: gpu.Buffer<uint32>) async throws -> gpu.Buffer<uint32> {
    let out = try await src.Device.CreateBuffer(of: uint32.self, count: indices.count)
    if indices.count > 0 {
        try await _gatherUint32.Launch(src, indices, out, over: indices.count)
    }
    return out
}

/// Scatter writes each element of src to dst at its index: dst[indices[i]]
/// = src[i]. Where two indices are the same, which write lands is not
/// defined.
public func Scatter(_ src: gpu.Buffer<uint32>, _ indices: gpu.Buffer<uint32>, into dst: gpu.Buffer<uint32>) async throws {
    if indices.count > 0 {
        try await _scatterUint32.Launch(src, indices, dst, over: indices.count)
    }
}

/// ScatterAdd adds each element of src into dst at its index, atomically:
/// dst[indices[i]] += src[i]. An integer sum is exact whatever the order; a
/// float32 one is not deterministic, as the order of the additions is not.
public func ScatterAdd(_ src: gpu.Buffer<uint32>, _ indices: gpu.Buffer<uint32>, into dst: gpu.Buffer<uint32>) async throws {
    if indices.count > 0 {
        try await _scatterAddUint32.Launch(src, indices, dst, over: indices.count)
    }
}
