// Generated by tools/gen.py; edit that, not this.
//
// Group-scope device functions: every work-item of a workgroup calls them
// together, as every one must reach gpu.Barrier(), and they return to each
// the same answer (a reduction) or its own (a scan). They are @inlinable, so
// a kernel in any module compiles them into itself; nothing is launched.
//
// Each goes through shared storage in a fixed order -- a tree for
// reductions, Hillis-Steele for scans -- so a result is the same on every
// device for the same group size, floating-point sums included. That is
// what lets the CPU device be their oracle bit for bit. A group holds at
// most MaxGroup work-items.
import "gpu"

/// MaxGroup is the most work-items a group-scope function supports.
public let MaxGroup = 1024

/// GroupRank is this work-item's index within its workgroup, counting x
/// fastest: the order the group-scope functions reduce and scan in.
@inlinable public func GroupRank() -> int {
    return gpu.LocalIndex.x + gpu.GroupSize.x * (gpu.LocalIndex.y + gpu.GroupSize.y * gpu.LocalIndex.z)
}

/// GroupCount is how many work-items the workgroup has.
@inlinable public func GroupCount() -> int {
    return gpu.GroupSize.x * gpu.GroupSize.y * gpu.GroupSize.z
}

/// _pow2 is the least power of two no smaller than n.
@inlinable public func _pow2(_ n: int) -> int {
    var w = 1
    while w < n {
        w *= 2
    }
    return w
}

/// GroupSum is the sum of x over the workgroup, added in a fixed tree order.
@inlinable public func GroupSum(_ x: float32) -> float32 {
    let s = gpu.Shared<float32>(count: 1024)
    let me = GroupRank()
    let n = GroupCount()
    s[me] = x
    gpu.Barrier()
    var stride = _pow2(n) / 2
    while stride > 0 {
        if me < stride && me + stride < n {
            let a = s[me]
            let b = s[me + stride]
            s[me] = a + b
        }
        gpu.Barrier()
        stride /= 2
    }
    let r = s[0]
    gpu.Barrier()
    return r
}

/// GroupMin is the least x in the workgroup.
@inlinable public func GroupMin(_ x: float32) -> float32 {
    let s = gpu.Shared<float32>(count: 1024)
    let me = GroupRank()
    let n = GroupCount()
    s[me] = x
    gpu.Barrier()
    var stride = _pow2(n) / 2
    while stride > 0 {
        if me < stride && me + stride < n {
            let a = s[me]
            let b = s[me + stride]
            s[me] = (b < a ? b : a)
        }
        gpu.Barrier()
        stride /= 2
    }
    let r = s[0]
    gpu.Barrier()
    return r
}

/// GroupMax is the greatest x in the workgroup.
@inlinable public func GroupMax(_ x: float32) -> float32 {
    let s = gpu.Shared<float32>(count: 1024)
    let me = GroupRank()
    let n = GroupCount()
    s[me] = x
    gpu.Barrier()
    var stride = _pow2(n) / 2
    while stride > 0 {
        if me < stride && me + stride < n {
            let a = s[me]
            let b = s[me + stride]
            s[me] = (b > a ? b : a)
        }
        gpu.Barrier()
        stride /= 2
    }
    let r = s[0]
    gpu.Barrier()
    return r
}

/// _groupScan is the inclusive and exclusive prefix sums of x at this
/// work-item, and the group's total, which is the last inclusive sum
/// exactly: the order a sum is taken in is the same for all three.
@inlinable public func _groupScan(_ x: float32) -> (inclusive: float32, exclusive: float32, total: float32) {
    let s = gpu.Shared<float32>(count: 1024)
    let me = GroupRank()
    let n = GroupCount()
    s[me] = x
    gpu.Barrier()
    var offset = 1
    while offset < n {
        var v = s[me]
        if me >= offset {
            v = s[me - offset] + v
        }
        gpu.Barrier()
        s[me] = v
        gpu.Barrier()
        offset *= 2
    }
    let inclusive = s[me]
    var exclusive = float32(0)
    if me > 0 {
        exclusive = s[me - 1]
    }
    let total = s[n - 1]
    gpu.Barrier()
    return (inclusive: inclusive, exclusive: exclusive, total: total)
}

/// GroupScan is the inclusive prefix sum of x up to and including this
/// work-item, in GroupRank order.
@inlinable public func GroupScan(_ x: float32) -> float32 {
    return _groupScan(x).inclusive
}

/// GroupExclusiveScan is the prefix sum of x before this work-item, and
/// the whole group's total.
@inlinable public func GroupExclusiveScan(_ x: float32) -> (prefix: float32, total: float32) {
    let r = _groupScan(x)
    return (prefix: r.exclusive, total: r.total)
}

/// GroupSum is the sum of x over the workgroup, added in a fixed tree order.
@inlinable public func GroupSum(_ x: int32) -> int32 {
    let s = gpu.Shared<int32>(count: 1024)
    let me = GroupRank()
    let n = GroupCount()
    s[me] = x
    gpu.Barrier()
    var stride = _pow2(n) / 2
    while stride > 0 {
        if me < stride && me + stride < n {
            let a = s[me]
            let b = s[me + stride]
            s[me] = a &+ b
        }
        gpu.Barrier()
        stride /= 2
    }
    let r = s[0]
    gpu.Barrier()
    return r
}

/// GroupMin is the least x in the workgroup.
@inlinable public func GroupMin(_ x: int32) -> int32 {
    let s = gpu.Shared<int32>(count: 1024)
    let me = GroupRank()
    let n = GroupCount()
    s[me] = x
    gpu.Barrier()
    var stride = _pow2(n) / 2
    while stride > 0 {
        if me < stride && me + stride < n {
            let a = s[me]
            let b = s[me + stride]
            s[me] = (b < a ? b : a)
        }
        gpu.Barrier()
        stride /= 2
    }
    let r = s[0]
    gpu.Barrier()
    return r
}

/// GroupMax is the greatest x in the workgroup.
@inlinable public func GroupMax(_ x: int32) -> int32 {
    let s = gpu.Shared<int32>(count: 1024)
    let me = GroupRank()
    let n = GroupCount()
    s[me] = x
    gpu.Barrier()
    var stride = _pow2(n) / 2
    while stride > 0 {
        if me < stride && me + stride < n {
            let a = s[me]
            let b = s[me + stride]
            s[me] = (b > a ? b : a)
        }
        gpu.Barrier()
        stride /= 2
    }
    let r = s[0]
    gpu.Barrier()
    return r
}

/// _groupScan is the inclusive and exclusive prefix sums of x at this
/// work-item, and the group's total, which is the last inclusive sum
/// exactly: the order a sum is taken in is the same for all three.
@inlinable public func _groupScan(_ x: int32) -> (inclusive: int32, exclusive: int32, total: int32) {
    let s = gpu.Shared<int32>(count: 1024)
    let me = GroupRank()
    let n = GroupCount()
    s[me] = x
    gpu.Barrier()
    var offset = 1
    while offset < n {
        var v = s[me]
        if me >= offset {
            v = s[me - offset] &+ v
        }
        gpu.Barrier()
        s[me] = v
        gpu.Barrier()
        offset *= 2
    }
    let inclusive = s[me]
    var exclusive = int32(0)
    if me > 0 {
        exclusive = s[me - 1]
    }
    let total = s[n - 1]
    gpu.Barrier()
    return (inclusive: inclusive, exclusive: exclusive, total: total)
}

/// GroupScan is the inclusive prefix sum of x up to and including this
/// work-item, in GroupRank order.
@inlinable public func GroupScan(_ x: int32) -> int32 {
    return _groupScan(x).inclusive
}

/// GroupExclusiveScan is the prefix sum of x before this work-item, and
/// the whole group's total.
@inlinable public func GroupExclusiveScan(_ x: int32) -> (prefix: int32, total: int32) {
    let r = _groupScan(x)
    return (prefix: r.exclusive, total: r.total)
}

/// GroupSum is the sum of x over the workgroup, added in a fixed tree order.
@inlinable public func GroupSum(_ x: uint32) -> uint32 {
    let s = gpu.Shared<uint32>(count: 1024)
    let me = GroupRank()
    let n = GroupCount()
    s[me] = x
    gpu.Barrier()
    var stride = _pow2(n) / 2
    while stride > 0 {
        if me < stride && me + stride < n {
            let a = s[me]
            let b = s[me + stride]
            s[me] = a &+ b
        }
        gpu.Barrier()
        stride /= 2
    }
    let r = s[0]
    gpu.Barrier()
    return r
}

/// GroupMin is the least x in the workgroup.
@inlinable public func GroupMin(_ x: uint32) -> uint32 {
    let s = gpu.Shared<uint32>(count: 1024)
    let me = GroupRank()
    let n = GroupCount()
    s[me] = x
    gpu.Barrier()
    var stride = _pow2(n) / 2
    while stride > 0 {
        if me < stride && me + stride < n {
            let a = s[me]
            let b = s[me + stride]
            s[me] = (b < a ? b : a)
        }
        gpu.Barrier()
        stride /= 2
    }
    let r = s[0]
    gpu.Barrier()
    return r
}

/// GroupMax is the greatest x in the workgroup.
@inlinable public func GroupMax(_ x: uint32) -> uint32 {
    let s = gpu.Shared<uint32>(count: 1024)
    let me = GroupRank()
    let n = GroupCount()
    s[me] = x
    gpu.Barrier()
    var stride = _pow2(n) / 2
    while stride > 0 {
        if me < stride && me + stride < n {
            let a = s[me]
            let b = s[me + stride]
            s[me] = (b > a ? b : a)
        }
        gpu.Barrier()
        stride /= 2
    }
    let r = s[0]
    gpu.Barrier()
    return r
}

/// _groupScan is the inclusive and exclusive prefix sums of x at this
/// work-item, and the group's total, which is the last inclusive sum
/// exactly: the order a sum is taken in is the same for all three.
@inlinable public func _groupScan(_ x: uint32) -> (inclusive: uint32, exclusive: uint32, total: uint32) {
    let s = gpu.Shared<uint32>(count: 1024)
    let me = GroupRank()
    let n = GroupCount()
    s[me] = x
    gpu.Barrier()
    var offset = 1
    while offset < n {
        var v = s[me]
        if me >= offset {
            v = s[me - offset] &+ v
        }
        gpu.Barrier()
        s[me] = v
        gpu.Barrier()
        offset *= 2
    }
    let inclusive = s[me]
    var exclusive = uint32(0)
    if me > 0 {
        exclusive = s[me - 1]
    }
    let total = s[n - 1]
    gpu.Barrier()
    return (inclusive: inclusive, exclusive: exclusive, total: total)
}

/// GroupScan is the inclusive prefix sum of x up to and including this
/// work-item, in GroupRank order.
@inlinable public func GroupScan(_ x: uint32) -> uint32 {
    return _groupScan(x).inclusive
}

/// GroupExclusiveScan is the prefix sum of x before this work-item, and
/// the whole group's total.
@inlinable public func GroupExclusiveScan(_ x: uint32) -> (prefix: uint32, total: uint32) {
    let r = _groupScan(x)
    return (prefix: r.exclusive, total: r.total)
}
