// Generated by tools/gen.py; edit that, not this.
//
// Reduce: a buffer to one value, a workgroup at a time, then the groups'
// results the same way, until one is left. Every step is GroupSum, GroupMin
// or GroupMax, so the order is fixed by the count and the result is the
// same on every device.
import "gpu"

/// Reduction is what Reduce combines elements with.
public enum Reduction {
    case Sum
    case Min
    case Max

    public var _code: int32 {
        switch self {
        case .Sum: return 0
        case .Min: return 1
        case .Max: return 2
        }
    }
}

/// ReduceGroup is how many work-items each of Reduce's groups has.
public let ReduceGroup = 256

func _reduceFloat32(_ x: gpu.Span<float32>, _ out: gpu.MutableSpan<float32>, _ n: int, _ op: int32) kernel {
    let i = gpu.Index.x
    var r = float32(0)
    if op == 0 {
        var v = float32(0)
        if i < n { v = x[i] }
        r = GroupSum(v)
    } else if op == 1 {
        var v = float32.infinity
        if i < n { v = x[i] }
        r = GroupMin(v)
    } else {
        var v = -float32.infinity
        if i < n { v = x[i] }
        r = GroupMax(v)
    }
    if GroupRank() == 0 {
        out[gpu.GroupIndex.x] = r
    }
}

/// Reduce combines every element of b with op: its sum, least or
/// greatest element. An empty buffer's is op's identity.
public func Reduce(_ b: gpu.Buffer<float32>, _ op: Reduction) async throws -> float32 {
    var n = b.count
    if n == 0 {
        switch op {
        case .Sum: return float32(0)
        case .Min: return float32.infinity
        case .Max: return -float32.infinity
        }
    }
    var cur = b
    while true {
        let groups = (n + 255) / 256
        let out = try await b.Device.CreateBuffer(of: float32.self, count: groups)
        try await _reduceFloat32.Launch(cur, out, n, op._code, over: groups * 256, workgroup: 256)
        if groups == 1 {
            return try await out.Download()[0]
        }
        cur = out
        n = groups
    }
}

func _reduceInt32(_ x: gpu.Span<int32>, _ out: gpu.MutableSpan<int32>, _ n: int, _ op: int32) kernel {
    let i = gpu.Index.x
    var r = int32(0)
    if op == 0 {
        var v = int32(0)
        if i < n { v = x[i] }
        r = GroupSum(v)
    } else if op == 1 {
        var v = int32.max
        if i < n { v = x[i] }
        r = GroupMin(v)
    } else {
        var v = int32.min
        if i < n { v = x[i] }
        r = GroupMax(v)
    }
    if GroupRank() == 0 {
        out[gpu.GroupIndex.x] = r
    }
}

/// Reduce combines every element of b with op: its sum, least or
/// greatest element. An empty buffer's is op's identity.
public func Reduce(_ b: gpu.Buffer<int32>, _ op: Reduction) async throws -> int32 {
    var n = b.count
    if n == 0 {
        switch op {
        case .Sum: return int32(0)
        case .Min: return int32.max
        case .Max: return int32.min
        }
    }
    var cur = b
    while true {
        let groups = (n + 255) / 256
        let out = try await b.Device.CreateBuffer(of: int32.self, count: groups)
        try await _reduceInt32.Launch(cur, out, n, op._code, over: groups * 256, workgroup: 256)
        if groups == 1 {
            return try await out.Download()[0]
        }
        cur = out
        n = groups
    }
}

func _reduceUint32(_ x: gpu.Span<uint32>, _ out: gpu.MutableSpan<uint32>, _ n: int, _ op: int32) kernel {
    let i = gpu.Index.x
    var r = uint32(0)
    if op == 0 {
        var v = uint32(0)
        if i < n { v = x[i] }
        r = GroupSum(v)
    } else if op == 1 {
        var v = uint32.max
        if i < n { v = x[i] }
        r = GroupMin(v)
    } else {
        var v = uint32(0)
        if i < n { v = x[i] }
        r = GroupMax(v)
    }
    if GroupRank() == 0 {
        out[gpu.GroupIndex.x] = r
    }
}

/// Reduce combines every element of b with op: its sum, least or
/// greatest element. An empty buffer's is op's identity.
public func Reduce(_ b: gpu.Buffer<uint32>, _ op: Reduction) async throws -> uint32 {
    var n = b.count
    if n == 0 {
        switch op {
        case .Sum: return uint32(0)
        case .Min: return uint32.max
        case .Max: return uint32(0)
        }
    }
    var cur = b
    while true {
        let groups = (n + 255) / 256
        let out = try await b.Device.CreateBuffer(of: uint32.self, count: groups)
        try await _reduceUint32.Launch(cur, out, n, op._code, over: groups * 256, workgroup: 256)
        if groups == 1 {
            return try await out.Download()[0]
        }
        cur = out
        n = groups
    }
}
