// Generated by tools/gen.py; edit that, not this.
//
// Scan: prefix sums of a buffer, in place. Each workgroup scans its own
// elements and writes its total; the totals are scanned (recursively, the
// same way) into each group's offset; the offsets are added in. The order
// of every addition is fixed by the count, so the result is the same on
// every device.
import "gpu"

func _scanBlocksFloat32(_ x: gpu.MutableSpan<float32>, _ sums: gpu.MutableSpan<float32>, _ n: int, _ exclusive: bool) kernel {
    let i = gpu.Index.x
    var v = float32(0)
    if i < n { v = x[i] }
    let r = _groupScan(v)
    if i < n {
        if exclusive {
            x[i] = r.exclusive
        } else {
            x[i] = r.inclusive
        }
    }
    if GroupRank() == 0 {
        sums[gpu.GroupIndex.x] = r.total
    }
}

func _addOffsetsFloat32(_ x: gpu.MutableSpan<float32>, _ offsets: gpu.Span<float32>, _ n: int) kernel {
    let i = gpu.Index.x
    if i < n {
        x[i] = offsets[gpu.GroupIndex.x] + x[i]
    }
}

/// Scan replaces each element of b with the sum of the elements up to
/// it: including itself (inclusive, the default), or before it
/// (exclusive, whose first element is zero).
public func Scan(_ b: gpu.Buffer<float32>, exclusive: bool = false) async throws {
    let n = b.count
    if n == 0 { return }
    let groups = (n + 255) / 256
    let sums = try await b.Device.CreateBuffer(of: float32.self, count: groups)
    try await _scanBlocksFloat32.Launch(b, sums, n, exclusive, over: groups * 256, workgroup: 256)
    if groups == 1 { return }
    try await Scan(sums, exclusive: true)
    try await _addOffsetsFloat32.Launch(b, sums, n, over: groups * 256, workgroup: 256)
}

func _scanBlocksInt32(_ x: gpu.MutableSpan<int32>, _ sums: gpu.MutableSpan<int32>, _ n: int, _ exclusive: bool) kernel {
    let i = gpu.Index.x
    var v = int32(0)
    if i < n { v = x[i] }
    let r = _groupScan(v)
    if i < n {
        if exclusive {
            x[i] = r.exclusive
        } else {
            x[i] = r.inclusive
        }
    }
    if GroupRank() == 0 {
        sums[gpu.GroupIndex.x] = r.total
    }
}

func _addOffsetsInt32(_ x: gpu.MutableSpan<int32>, _ offsets: gpu.Span<int32>, _ n: int) kernel {
    let i = gpu.Index.x
    if i < n {
        x[i] = offsets[gpu.GroupIndex.x] &+ x[i]
    }
}

/// Scan replaces each element of b with the sum of the elements up to
/// it: including itself (inclusive, the default), or before it
/// (exclusive, whose first element is zero).
public func Scan(_ b: gpu.Buffer<int32>, exclusive: bool = false) async throws {
    let n = b.count
    if n == 0 { return }
    let groups = (n + 255) / 256
    let sums = try await b.Device.CreateBuffer(of: int32.self, count: groups)
    try await _scanBlocksInt32.Launch(b, sums, n, exclusive, over: groups * 256, workgroup: 256)
    if groups == 1 { return }
    try await Scan(sums, exclusive: true)
    try await _addOffsetsInt32.Launch(b, sums, n, over: groups * 256, workgroup: 256)
}

func _scanBlocksUint32(_ x: gpu.MutableSpan<uint32>, _ sums: gpu.MutableSpan<uint32>, _ n: int, _ exclusive: bool) kernel {
    let i = gpu.Index.x
    var v = uint32(0)
    if i < n { v = x[i] }
    let r = _groupScan(v)
    if i < n {
        if exclusive {
            x[i] = r.exclusive
        } else {
            x[i] = r.inclusive
        }
    }
    if GroupRank() == 0 {
        sums[gpu.GroupIndex.x] = r.total
    }
}

func _addOffsetsUint32(_ x: gpu.MutableSpan<uint32>, _ offsets: gpu.Span<uint32>, _ n: int) kernel {
    let i = gpu.Index.x
    if i < n {
        x[i] = offsets[gpu.GroupIndex.x] &+ x[i]
    }
}

/// Scan replaces each element of b with the sum of the elements up to
/// it: including itself (inclusive, the default), or before it
/// (exclusive, whose first element is zero).
public func Scan(_ b: gpu.Buffer<uint32>, exclusive: bool = false) async throws {
    let n = b.count
    if n == 0 { return }
    let groups = (n + 255) / 256
    let sums = try await b.Device.CreateBuffer(of: uint32.self, count: groups)
    try await _scanBlocksUint32.Launch(b, sums, n, exclusive, over: groups * 256, workgroup: 256)
    if groups == 1 { return }
    try await Scan(sums, exclusive: true)
    try await _addOffsetsUint32.Launch(b, sums, n, over: groups * 256, workgroup: 256)
}
