// Generated by tools/gen.py; edit that, not this.
//
// Select: the elements of a buffer that satisfy a condition, in the order
// they came in -- stream compaction. Each element is tested into a flag,
// the flags are scanned into where each kept element goes, and the kept
// elements are written there.
import "gpu"

/// Where is the condition Select, SelectIndices and Count keep an element
/// by: how it compares with a value. For integer elements the comparison
/// is exact -- Less(0.5) keeps 0 and below, Less(-1) keeps no uint32 --
/// and for float32 ones the value is rounded to float32 first.
public enum Where {
    case Less(float64)
    case LessEqual(float64)
    case Greater(float64)
    case GreaterEqual(float64)
    case Equal(float64)
    case NotEqual(float64)

    public var _code: int32 {
        switch self {
        case .Less: return 0
        case .LessEqual: return 1
        case .Greater: return 2
        case .GreaterEqual: return 3
        case .Equal: return 4
        case .NotEqual: return 5
        }
    }

    /// _bounds is the comparison for an integer type whose values run
    /// from lo to hi: an operator and an integral value in that range, or
    /// 6 (always) or 7 (never) where the value is outside it.
    public func _bounds(_ lo: float64, _ hi: float64) -> (int32, float64) {
        let v = _value
        let up = v.rounded(.up)
        let down = v.rounded(.down)
        switch self {
        case .Less:
            return up <= lo ? (7, 0) : up > hi ? (6, 0) : (0, up)
        case .LessEqual:
            return down < lo ? (7, 0) : down >= hi ? (6, 0) : (1, down)
        case .Greater:
            return down < lo ? (6, 0) : down >= hi ? (7, 0) : (2, down)
        case .GreaterEqual:
            return up <= lo ? (6, 0) : up > hi ? (7, 0) : (3, up)
        case .Equal:
            return v != down || v < lo || v > hi ? (7, 0) : (4, v)
        case .NotEqual:
            return v != down || v < lo || v > hi ? (6, 0) : (5, v)
        }
    }

    public var _value: float64 {
        switch self {
        case .Less(let v): return v
        case .LessEqual(let v): return v
        case .Greater(let v): return v
        case .GreaterEqual(let v): return v
        case .Equal(let v): return v
        case .NotEqual(let v): return v
        }
    }
}

@inlinable public func _testFloat32(_ x: float32, _ op: int32, _ v: float32) -> bool {
    if op == 0 { return x < v }
    if op == 1 { return x <= v }
    if op == 2 { return x > v }
    if op == 3 { return x >= v }
    if op == 4 { return x == v }
    if op == 5 { return x != v }
    return op == 6
}

func _flagFloat32(_ x: gpu.Span<float32>, _ flags: gpu.MutableSpan<uint32>, _ op: int32, _ v: float32) kernel {
    let i = gpu.Index.x
    if i < x.count {
        flags[i] = _testFloat32(x[i], op, v) ? 1 : 0
    }
}

func _compactFloat32(_ x: gpu.Span<float32>, _ at: gpu.Span<uint32>, _ out: gpu.MutableSpan<float32>, _ indices: gpu.MutableSpan<uint32>, _ op: int32, _ v: float32, _ values: bool) kernel {
    let i = gpu.Index.x
    if i < x.count && _testFloat32(x[i], op, v) {
        if values {
            out[int(at[i])] = x[i]
        } else {
            indices[int(at[i])] = uint32(i)
        }
    }
}

/// _opFloat32 is w as an operator and a value of float32.
func _opFloat32(_ w: Where) -> (int32, float32) {
    return (w._code, float32(w._value))
}

/// _whereFloat32 is where each kept element of b goes, and how many there are.
func _whereFloat32(_ b: gpu.Buffer<float32>, _ w: Where) async throws -> (gpu.Buffer<uint32>, int) {
    let flags = try await b.Device.CreateBuffer(of: uint32.self, count: b.count)
    let (op, v) = _opFloat32(w)
    try await _flagFloat32.Launch(b, flags, op, v, over: b.count)
    let kept = int(try await Reduce(flags, .Sum))
    try await Scan(flags, exclusive: true)
    return (flags, kept)
}

/// Count is how many elements of b satisfy w.
public func Count(_ b: gpu.Buffer<float32>, where w: Where) async throws -> int {
    if b.count == 0 { return 0 }
    let flags = try await b.Device.CreateBuffer(of: uint32.self, count: b.count)
    let (op, v) = _opFloat32(w)
    try await _flagFloat32.Launch(b, flags, op, v, over: b.count)
    return int(try await Reduce(flags, .Sum))
}

/// Select is the elements of b that satisfy w, in their order in b.
public func Select(_ b: gpu.Buffer<float32>, where w: Where) async throws -> gpu.Buffer<float32> {
    if b.count == 0 { return try await b.Device.CreateBuffer(of: float32.self, count: 0) }
    let (at, kept) = try await _whereFloat32(b, w)
    let out = try await b.Device.CreateBuffer(of: float32.self, count: kept)
    if kept > 0 {
        let (op, v) = _opFloat32(w)
        try await _compactFloat32.Launch(b, at, out, at, op, v, true, over: b.count)
    }
    return out
}

/// SelectIndices is where in b the elements that satisfy w are, in
/// ascending order.
public func SelectIndices(_ b: gpu.Buffer<float32>, where w: Where) async throws -> gpu.Buffer<uint32> {
    if b.count == 0 { return try await b.Device.CreateBuffer(of: uint32.self, count: 0) }
    let (at, kept) = try await _whereFloat32(b, w)
    let out = try await b.Device.CreateBuffer(of: uint32.self, count: kept)
    if kept > 0 {
        let (op, v) = _opFloat32(w)
        try await _compactFloat32.Launch(b, at, b, out, op, v, false, over: b.count)
    }
    return out
}

@inlinable public func _testInt32(_ x: int32, _ op: int32, _ v: int32) -> bool {
    if op == 0 { return x < v }
    if op == 1 { return x <= v }
    if op == 2 { return x > v }
    if op == 3 { return x >= v }
    if op == 4 { return x == v }
    if op == 5 { return x != v }
    return op == 6
}

func _flagInt32(_ x: gpu.Span<int32>, _ flags: gpu.MutableSpan<uint32>, _ op: int32, _ v: int32) kernel {
    let i = gpu.Index.x
    if i < x.count {
        flags[i] = _testInt32(x[i], op, v) ? 1 : 0
    }
}

func _compactInt32(_ x: gpu.Span<int32>, _ at: gpu.Span<uint32>, _ out: gpu.MutableSpan<int32>, _ indices: gpu.MutableSpan<uint32>, _ op: int32, _ v: int32, _ values: bool) kernel {
    let i = gpu.Index.x
    if i < x.count && _testInt32(x[i], op, v) {
        if values {
            out[int(at[i])] = x[i]
        } else {
            indices[int(at[i])] = uint32(i)
        }
    }
}

/// _opInt32 is w as an operator and a value of int32.
func _opInt32(_ w: Where) -> (int32, int32) {
    let (op, v) = w._bounds(-2147483648, 2147483647)
    return (op, int32(v))
}

/// _whereInt32 is where each kept element of b goes, and how many there are.
func _whereInt32(_ b: gpu.Buffer<int32>, _ w: Where) async throws -> (gpu.Buffer<uint32>, int) {
    let flags = try await b.Device.CreateBuffer(of: uint32.self, count: b.count)
    let (op, v) = _opInt32(w)
    try await _flagInt32.Launch(b, flags, op, v, over: b.count)
    let kept = int(try await Reduce(flags, .Sum))
    try await Scan(flags, exclusive: true)
    return (flags, kept)
}

/// Count is how many elements of b satisfy w.
public func Count(_ b: gpu.Buffer<int32>, where w: Where) async throws -> int {
    if b.count == 0 { return 0 }
    let flags = try await b.Device.CreateBuffer(of: uint32.self, count: b.count)
    let (op, v) = _opInt32(w)
    try await _flagInt32.Launch(b, flags, op, v, over: b.count)
    return int(try await Reduce(flags, .Sum))
}

/// Select is the elements of b that satisfy w, in their order in b.
public func Select(_ b: gpu.Buffer<int32>, where w: Where) async throws -> gpu.Buffer<int32> {
    if b.count == 0 { return try await b.Device.CreateBuffer(of: int32.self, count: 0) }
    let (at, kept) = try await _whereInt32(b, w)
    let out = try await b.Device.CreateBuffer(of: int32.self, count: kept)
    if kept > 0 {
        let (op, v) = _opInt32(w)
        try await _compactInt32.Launch(b, at, out, at, op, v, true, over: b.count)
    }
    return out
}

/// SelectIndices is where in b the elements that satisfy w are, in
/// ascending order.
public func SelectIndices(_ b: gpu.Buffer<int32>, where w: Where) async throws -> gpu.Buffer<uint32> {
    if b.count == 0 { return try await b.Device.CreateBuffer(of: uint32.self, count: 0) }
    let (at, kept) = try await _whereInt32(b, w)
    let out = try await b.Device.CreateBuffer(of: uint32.self, count: kept)
    if kept > 0 {
        let (op, v) = _opInt32(w)
        try await _compactInt32.Launch(b, at, b, out, op, v, false, over: b.count)
    }
    return out
}

@inlinable public func _testUint32(_ x: uint32, _ op: int32, _ v: uint32) -> bool {
    if op == 0 { return x < v }
    if op == 1 { return x <= v }
    if op == 2 { return x > v }
    if op == 3 { return x >= v }
    if op == 4 { return x == v }
    if op == 5 { return x != v }
    return op == 6
}

func _flagUint32(_ x: gpu.Span<uint32>, _ flags: gpu.MutableSpan<uint32>, _ op: int32, _ v: uint32) kernel {
    let i = gpu.Index.x
    if i < x.count {
        flags[i] = _testUint32(x[i], op, v) ? 1 : 0
    }
}

func _compactUint32(_ x: gpu.Span<uint32>, _ at: gpu.Span<uint32>, _ out: gpu.MutableSpan<uint32>, _ indices: gpu.MutableSpan<uint32>, _ op: int32, _ v: uint32, _ values: bool) kernel {
    let i = gpu.Index.x
    if i < x.count && _testUint32(x[i], op, v) {
        if values {
            out[int(at[i])] = x[i]
        } else {
            indices[int(at[i])] = uint32(i)
        }
    }
}

/// _opUint32 is w as an operator and a value of uint32.
func _opUint32(_ w: Where) -> (int32, uint32) {
    let (op, v) = w._bounds(0, 4294967295)
    return (op, uint32(v))
}

/// _whereUint32 is where each kept element of b goes, and how many there are.
func _whereUint32(_ b: gpu.Buffer<uint32>, _ w: Where) async throws -> (gpu.Buffer<uint32>, int) {
    let flags = try await b.Device.CreateBuffer(of: uint32.self, count: b.count)
    let (op, v) = _opUint32(w)
    try await _flagUint32.Launch(b, flags, op, v, over: b.count)
    let kept = int(try await Reduce(flags, .Sum))
    try await Scan(flags, exclusive: true)
    return (flags, kept)
}

/// Count is how many elements of b satisfy w.
public func Count(_ b: gpu.Buffer<uint32>, where w: Where) async throws -> int {
    if b.count == 0 { return 0 }
    let flags = try await b.Device.CreateBuffer(of: uint32.self, count: b.count)
    let (op, v) = _opUint32(w)
    try await _flagUint32.Launch(b, flags, op, v, over: b.count)
    return int(try await Reduce(flags, .Sum))
}

/// Select is the elements of b that satisfy w, in their order in b.
public func Select(_ b: gpu.Buffer<uint32>, where w: Where) async throws -> gpu.Buffer<uint32> {
    if b.count == 0 { return try await b.Device.CreateBuffer(of: uint32.self, count: 0) }
    let (at, kept) = try await _whereUint32(b, w)
    let out = try await b.Device.CreateBuffer(of: uint32.self, count: kept)
    if kept > 0 {
        let (op, v) = _opUint32(w)
        try await _compactUint32.Launch(b, at, out, at, op, v, true, over: b.count)
    }
    return out
}

/// SelectIndices is where in b the elements that satisfy w are, in
/// ascending order.
public func SelectIndices(_ b: gpu.Buffer<uint32>, where w: Where) async throws -> gpu.Buffer<uint32> {
    if b.count == 0 { return try await b.Device.CreateBuffer(of: uint32.self, count: 0) }
    let (at, kept) = try await _whereUint32(b, w)
    let out = try await b.Device.CreateBuffer(of: uint32.self, count: kept)
    if kept > 0 {
        let (op, v) = _opUint32(w)
        try await _compactUint32.Launch(b, at, b, out, op, v, false, over: b.count)
    }
    return out
}
