#!/usr/bin/env python3
"""Writes the per-element-type .vs files of gpu/parallel.

Kernels are not generic yet (proposed_vertex_kernel.md K1), so each
function is written once per element type. This keeps the copies
identical; when kernels are generic, the generated files collapse into
one generic definition each and this script goes away.

Run from the repository root: python3 tools/gen.py
"""

HEADER = "// Generated by tools/gen.py; edit that, not this.\n"

# (type, zero, identity for Min, identity for Max, addition operator)
TYPES = [
    ("float32", "float32(0)", "float32.infinity", "-float32.infinity", "+"),
    ("int32", "int32(0)", "int32.max", "int32.min", "&+"),
    ("uint32", "uint32(0)", "uint32.max", "uint32(0)", "&+"),
]


def group():
    out = [HEADER, '''//
// Group-scope device functions: every work-item of a workgroup calls them
// together, as every one must reach gpu.Barrier(), and they return to each
// the same answer (a reduction) or its own (a scan). They are @inlinable, so
// a kernel in any module compiles them into itself; nothing is launched.
//
// Each goes through shared storage in a fixed order -- a tree for
// reductions, Hillis-Steele for scans -- so a result is the same on every
// device for the same group size, floating-point sums included. That is
// what lets the CPU device be their oracle bit for bit. A group holds at
// most MaxGroup work-items.
import "gpu"

/// MaxGroup is the most work-items a group-scope function supports.
public let MaxGroup = 1024

/// GroupRank is this work-item's index within its workgroup, counting x
/// fastest: the order the group-scope functions reduce and scan in.
@inlinable public func GroupRank() -> int {
    return gpu.LocalIndex.x + gpu.GroupSize.x * (gpu.LocalIndex.y + gpu.GroupSize.y * gpu.LocalIndex.z)
}

/// GroupCount is how many work-items the workgroup has.
@inlinable public func GroupCount() -> int {
    return gpu.GroupSize.x * gpu.GroupSize.y * gpu.GroupSize.z
}

/// _pow2 is the least power of two no smaller than n.
@inlinable public func _pow2(_ n: int) -> int {
    var w = 1
    while w < n {
        w *= 2
    }
    return w
}
''']
    for t, zero, maxv, minv, add in TYPES:
        for name, expr, doc in [
            ("Sum", f"a {add} b", "the sum of x over the workgroup, added in a fixed tree order"),
            ("Min", "(b < a ? b : a)", "the least x in the workgroup"),
            ("Max", "(b > a ? b : a)", "the greatest x in the workgroup"),
        ]:
            out.append(f'''
/// Group{name} is {doc}.
@inlinable public func Group{name}(_ x: {t}) -> {t} {{
    let s = gpu.Shared<{t}>(count: 1024)
    let me = GroupRank()
    let n = GroupCount()
    s[me] = x
    gpu.Barrier()
    var stride = _pow2(n) / 2
    while stride > 0 {{
        if me < stride && me + stride < n {{
            let a = s[me]
            let b = s[me + stride]
            s[me] = {expr}
        }}
        gpu.Barrier()
        stride /= 2
    }}
    let r = s[0]
    gpu.Barrier()
    return r
}}
''')
        out.append(f'''
/// _groupScan is the inclusive and exclusive prefix sums of x at this
/// work-item, and the group's total, which is the last inclusive sum
/// exactly: the order a sum is taken in is the same for all three.
@inlinable public func _groupScan(_ x: {t}) -> (inclusive: {t}, exclusive: {t}, total: {t}) {{
    let s = gpu.Shared<{t}>(count: 1024)
    let me = GroupRank()
    let n = GroupCount()
    s[me] = x
    gpu.Barrier()
    var offset = 1
    while offset < n {{
        var v = s[me]
        if me >= offset {{
            v = s[me - offset] {add} v
        }}
        gpu.Barrier()
        s[me] = v
        gpu.Barrier()
        offset *= 2
    }}
    let inclusive = s[me]
    var exclusive = {zero}
    if me > 0 {{
        exclusive = s[me - 1]
    }}
    let total = s[n - 1]
    gpu.Barrier()
    return (inclusive: inclusive, exclusive: exclusive, total: total)
}}

/// GroupScan is the inclusive prefix sum of x up to and including this
/// work-item, in GroupRank order.
@inlinable public func GroupScan(_ x: {t}) -> {t} {{
    return _groupScan(x).inclusive
}}

/// GroupExclusiveScan is the prefix sum of x before this work-item, and
/// the whole group's total.
@inlinable public func GroupExclusiveScan(_ x: {t}) -> (prefix: {t}, total: {t}) {{
    let r = _groupScan(x)
    return (prefix: r.exclusive, total: r.total)
}}
''')
    return "".join(out)


def reduce():
    out = [HEADER, '''//
// Reduce: a buffer to one value, a workgroup at a time, then the groups'
// results the same way, until one is left. Every step is GroupSum, GroupMin
// or GroupMax, so the order is fixed by the count and the result is the
// same on every device.
import "gpu"

/// Reduction is what Reduce combines elements with.
public enum Reduction {
    case Sum
    case Min
    case Max

    public var _code: int32 {
        switch self {
        case .Sum: return 0
        case .Min: return 1
        case .Max: return 2
        }
    }
}

/// ReduceGroup is how many work-items each of Reduce's groups has.
public let ReduceGroup = 256
''']
    for t, zero, maxv, minv, add in TYPES:
        T = t[0].upper() + t[1:]
        out.append(f'''
func _reduce{T}(_ x: gpu.Span<{t}>, _ out: gpu.MutableSpan<{t}>, _ n: int, _ op: int32) kernel {{
    let i = gpu.Index.x
    var r = {zero}
    if op == 0 {{
        var v = {zero}
        if i < n {{ v = x[i] }}
        r = GroupSum(v)
    }} else if op == 1 {{
        var v = {maxv}
        if i < n {{ v = x[i] }}
        r = GroupMin(v)
    }} else {{
        var v = {minv}
        if i < n {{ v = x[i] }}
        r = GroupMax(v)
    }}
    if GroupRank() == 0 {{
        out[gpu.GroupIndex.x] = r
    }}
}}

/// Reduce combines every element of b with op: its sum, least or
/// greatest element. An empty buffer's is op's identity.
public func Reduce(_ b: gpu.Buffer<{t}>, _ op: Reduction) async throws -> {t} {{
    var n = b.count
    if n == 0 {{
        switch op {{
        case .Sum: return {zero}
        case .Min: return {maxv}
        case .Max: return {minv}
        }}
    }}
    var cur = b
    while true {{
        let groups = (n + 255) / 256
        let out = try await b.Device.CreateBuffer(of: {t}.self, count: groups)
        try await _reduce{T}.Launch(cur, out, n, op._code, over: groups * 256, workgroup: 256)
        if groups == 1 {{
            return try await out.Download()[0]
        }}
        cur = out
        n = groups
    }}
}}
''')
    return "".join(out)


def scan():
    out = [HEADER, '''//
// Scan: prefix sums of a buffer, in place. Each workgroup scans its own
// elements and writes its total; the totals are scanned (recursively, the
// same way) into each group's offset; the offsets are added in. The order
// of every addition is fixed by the count, so the result is the same on
// every device.
import "gpu"
''']
    for t, zero, maxv, minv, add in TYPES:
        T = t[0].upper() + t[1:]
        out.append(f'''
func _scanBlocks{T}(_ x: gpu.MutableSpan<{t}>, _ sums: gpu.MutableSpan<{t}>, _ n: int, _ exclusive: bool) kernel {{
    let i = gpu.Index.x
    var v = {zero}
    if i < n {{ v = x[i] }}
    let r = _groupScan(v)
    if i < n {{
        if exclusive {{
            x[i] = r.exclusive
        }} else {{
            x[i] = r.inclusive
        }}
    }}
    if GroupRank() == 0 {{
        sums[gpu.GroupIndex.x] = r.total
    }}
}}

func _addOffsets{T}(_ x: gpu.MutableSpan<{t}>, _ offsets: gpu.Span<{t}>, _ n: int) kernel {{
    let i = gpu.Index.x
    if i < n {{
        x[i] = offsets[gpu.GroupIndex.x] {add} x[i]
    }}
}}

/// Scan replaces each element of b with the sum of the elements up to
/// it: including itself (inclusive, the default), or before it
/// (exclusive, whose first element is zero).
public func Scan(_ b: gpu.Buffer<{t}>, exclusive: bool = false) async throws {{
    let n = b.count
    if n == 0 {{ return }}
    let groups = (n + 255) / 256
    let sums = try await b.Device.CreateBuffer(of: {t}.self, count: groups)
    try await _scanBlocks{T}.Launch(b, sums, n, exclusive, over: groups * 256, workgroup: 256)
    if groups == 1 {{ return }}
    try await Scan(sums, exclusive: true)
    try await _addOffsets{T}.Launch(b, sums, n, over: groups * 256, workgroup: 256)
}}
''')
    return "".join(out)


def main():
    for name, text in [("group", group()), ("reduce", reduce()), ("scan", scan())]:
        with open(f"parallel/{name}.vs", "w") as f:
            f.write(text)


if __name__ == "__main__":
    main()
