#!/usr/bin/env python3
"""Writes the per-element-type .vs files of gpu/parallel.

Kernels are not generic yet (proposed_vertex_kernel.md K1), so each
function is written once per element type. This keeps the copies
identical; when kernels are generic, the generated files collapse into
one generic definition each and this script goes away.

Run from the repository root: python3 tools/gen.py
"""

HEADER = "// Generated by tools/gen.py; edit that, not this.\n"

# (type, zero, identity for Min, identity for Max, addition operator)
TYPES = [
    ("float32", "float32(0)", "float32.infinity", "-float32.infinity", "+"),
    ("int32", "int32(0)", "int32.max", "int32.min", "&+"),
    ("uint32", "uint32(0)", "uint32.max", "uint32(0)", "&+"),
]


def group():
    out = [HEADER, '''//
// Group-scope device functions: every work-item of a workgroup calls them
// together, as every one must reach gpu.Barrier(), and they return to each
// the same answer (a reduction) or its own (a scan). They are @inlinable, so
// a kernel in any module compiles them into itself; nothing is launched.
//
// Each goes through shared storage in a fixed order -- a tree for
// reductions, Hillis-Steele for scans -- so a result is the same on every
// device for the same group size, floating-point sums included. That is
// what lets the CPU device be their oracle bit for bit. A group holds at
// most MaxGroup work-items.
import "gpu"

/// MaxGroup is the most work-items a group-scope function supports.
public let MaxGroup = 1024

/// GroupRank is this work-item's index within its workgroup, counting x
/// fastest: the order the group-scope functions reduce and scan in.
@inlinable public func GroupRank() -> int {
    return gpu.LocalIndex.x + gpu.GroupSize.x * (gpu.LocalIndex.y + gpu.GroupSize.y * gpu.LocalIndex.z)
}

/// GroupCount is how many work-items the workgroup has.
@inlinable public func GroupCount() -> int {
    return gpu.GroupSize.x * gpu.GroupSize.y * gpu.GroupSize.z
}

/// _pow2 is the least power of two no smaller than n.
@inlinable public func _pow2(_ n: int) -> int {
    var w = 1
    while w < n {
        w *= 2
    }
    return w
}
''']
    for t, zero, maxv, minv, add in TYPES:
        for name, expr, doc in [
            ("Sum", f"a {add} b", "the sum of x over the workgroup, added in a fixed tree order"),
            ("Min", "(b < a ? b : a)", "the least x in the workgroup"),
            ("Max", "(b > a ? b : a)", "the greatest x in the workgroup"),
        ]:
            out.append(f'''
/// Group{name} is {doc}.
@inlinable public func Group{name}(_ x: {t}) -> {t} {{
    let s = gpu.Shared<{t}>(count: 1024)
    let me = GroupRank()
    let n = GroupCount()
    s[me] = x
    gpu.Barrier()
    var stride = _pow2(n) / 2
    while stride > 0 {{
        if me < stride && me + stride < n {{
            let a = s[me]
            let b = s[me + stride]
            s[me] = {expr}
        }}
        gpu.Barrier()
        stride /= 2
    }}
    let r = s[0]
    gpu.Barrier()
    return r
}}
''')
        out.append(f'''
/// _groupScan is the inclusive and exclusive prefix sums of x at this
/// work-item, and the group's total, which is the last inclusive sum
/// exactly: the order a sum is taken in is the same for all three.
@inlinable public func _groupScan(_ x: {t}) -> (inclusive: {t}, exclusive: {t}, total: {t}) {{
    let s = gpu.Shared<{t}>(count: 1024)
    let me = GroupRank()
    let n = GroupCount()
    s[me] = x
    gpu.Barrier()
    var offset = 1
    while offset < n {{
        var v = s[me]
        if me >= offset {{
            v = s[me - offset] {add} v
        }}
        gpu.Barrier()
        s[me] = v
        gpu.Barrier()
        offset *= 2
    }}
    let inclusive = s[me]
    var exclusive = {zero}
    if me > 0 {{
        exclusive = s[me - 1]
    }}
    let total = s[n - 1]
    gpu.Barrier()
    return (inclusive: inclusive, exclusive: exclusive, total: total)
}}

/// GroupScan is the inclusive prefix sum of x up to and including this
/// work-item, in GroupRank order.
@inlinable public func GroupScan(_ x: {t}) -> {t} {{
    return _groupScan(x).inclusive
}}

/// GroupExclusiveScan is the prefix sum of x before this work-item, and
/// the whole group's total.
@inlinable public func GroupExclusiveScan(_ x: {t}) -> (prefix: {t}, total: {t}) {{
    let r = _groupScan(x)
    return (prefix: r.exclusive, total: r.total)
}}
''')
    return "".join(out)


def reduce():
    out = [HEADER, '''//
// Reduce: a buffer to one value, a workgroup at a time, then the groups'
// results the same way, until one is left. Every step is GroupSum, GroupMin
// or GroupMax, so the order is fixed by the count and the result is the
// same on every device.
import "gpu"

/// Reduction is what Reduce combines elements with.
public enum Reduction {
    case Sum
    case Min
    case Max

    public var _code: int32 {
        switch self {
        case .Sum: return 0
        case .Min: return 1
        case .Max: return 2
        }
    }
}

/// ReduceGroup is how many work-items each of Reduce's groups has.
public let ReduceGroup = 256
''']
    for t, zero, maxv, minv, add in TYPES:
        T = t[0].upper() + t[1:]
        out.append(f'''
func _reduce{T}(_ x: gpu.Span<{t}>, _ out: gpu.MutableSpan<{t}>, _ n: int, _ op: int32) kernel {{
    let i = gpu.Index.x
    var r = {zero}
    if op == 0 {{
        var v = {zero}
        if i < n {{ v = x[i] }}
        r = GroupSum(v)
    }} else if op == 1 {{
        var v = {maxv}
        if i < n {{ v = x[i] }}
        r = GroupMin(v)
    }} else {{
        var v = {minv}
        if i < n {{ v = x[i] }}
        r = GroupMax(v)
    }}
    if GroupRank() == 0 {{
        out[gpu.GroupIndex.x] = r
    }}
}}

/// Reduce combines every element of b with op: its sum, least or
/// greatest element. An empty buffer's is op's identity.
public func Reduce(_ b: gpu.Buffer<{t}>, _ op: Reduction) async throws -> {t} {{
    var n = b.count
    if n == 0 {{
        switch op {{
        case .Sum: return {zero}
        case .Min: return {maxv}
        case .Max: return {minv}
        }}
    }}
    var cur = b
    while true {{
        let groups = (n + 255) / 256
        let out = try await b.Device.CreateBuffer(of: {t}.self, count: groups)
        try await _reduce{T}.Launch(cur, out, n, op._code, over: groups * 256, workgroup: 256)
        if groups == 1 {{
            return try await out.Download()[0]
        }}
        cur = out
        n = groups
    }}
}}
''')
    return "".join(out)


def scan():
    out = [HEADER, '''//
// Scan: prefix sums of a buffer, in place. Each workgroup scans its own
// elements and writes its total; the totals are scanned (recursively, the
// same way) into each group's offset; the offsets are added in. The order
// of every addition is fixed by the count, so the result is the same on
// every device.
import "gpu"
''']
    for t, zero, maxv, minv, add in TYPES:
        T = t[0].upper() + t[1:]
        out.append(f'''
func _scanBlocks{T}(_ x: gpu.MutableSpan<{t}>, _ sums: gpu.MutableSpan<{t}>, _ n: int, _ exclusive: bool) kernel {{
    let i = gpu.Index.x
    var v = {zero}
    if i < n {{ v = x[i] }}
    let r = _groupScan(v)
    if i < n {{
        if exclusive {{
            x[i] = r.exclusive
        }} else {{
            x[i] = r.inclusive
        }}
    }}
    if GroupRank() == 0 {{
        sums[gpu.GroupIndex.x] = r.total
    }}
}}

func _addOffsets{T}(_ x: gpu.MutableSpan<{t}>, _ offsets: gpu.Span<{t}>, _ n: int) kernel {{
    let i = gpu.Index.x
    if i < n {{
        x[i] = offsets[gpu.GroupIndex.x] {add} x[i]
    }}
}}

/// Scan replaces each element of b with the sum of the elements up to
/// it: including itself (inclusive, the default), or before it
/// (exclusive, whose first element is zero).
public func Scan(_ b: gpu.Buffer<{t}>, exclusive: bool = false) async throws {{
    let n = b.count
    if n == 0 {{ return }}
    let groups = (n + 255) / 256
    let sums = try await b.Device.CreateBuffer(of: {t}.self, count: groups)
    try await _scanBlocks{T}.Launch(b, sums, n, exclusive, over: groups * 256, workgroup: 256)
    if groups == 1 {{ return }}
    try await Scan(sums, exclusive: true)
    try await _addOffsets{T}.Launch(b, sums, n, over: groups * 256, workgroup: 256)
}}
''')
    return "".join(out)


def select():
    out = [HEADER, '''//
// Select: the elements of a buffer that satisfy a condition, in the order
// they came in -- stream compaction. Each element is tested into a flag,
// the flags are scanned into where each kept element goes, and the kept
// elements are written there.
import "gpu"

/// Where is the condition Select, SelectIndices and Count keep an element
/// by: how it compares with a value. For integer elements the comparison
/// is exact -- Less(0.5) keeps 0 and below, Less(-1) keeps no uint32 --
/// and for float32 ones the value is rounded to float32 first.
public enum Where {
    case Less(float64)
    case LessEqual(float64)
    case Greater(float64)
    case GreaterEqual(float64)
    case Equal(float64)
    case NotEqual(float64)

    public var _code: int32 {
        switch self {
        case .Less: return 0
        case .LessEqual: return 1
        case .Greater: return 2
        case .GreaterEqual: return 3
        case .Equal: return 4
        case .NotEqual: return 5
        }
    }

    /// _bounds is the comparison for an integer type whose values run
    /// from lo to hi: an operator and an integral value in that range, or
    /// 6 (always) or 7 (never) where the value is outside it.
    public func _bounds(_ lo: float64, _ hi: float64) -> (int32, float64) {
        let v = _value
        let up = v.rounded(.up)
        let down = v.rounded(.down)
        switch self {
        case .Less:
            return up <= lo ? (7, 0) : up > hi ? (6, 0) : (0, up)
        case .LessEqual:
            return down < lo ? (7, 0) : down >= hi ? (6, 0) : (1, down)
        case .Greater:
            return down < lo ? (6, 0) : down >= hi ? (7, 0) : (2, down)
        case .GreaterEqual:
            return up <= lo ? (6, 0) : up > hi ? (7, 0) : (3, up)
        case .Equal:
            return v != down || v < lo || v > hi ? (7, 0) : (4, v)
        case .NotEqual:
            return v != down || v < lo || v > hi ? (6, 0) : (5, v)
        }
    }

    public var _value: float64 {
        switch self {
        case .Less(let v): return v
        case .LessEqual(let v): return v
        case .Greater(let v): return v
        case .GreaterEqual(let v): return v
        case .Equal(let v): return v
        case .NotEqual(let v): return v
        }
    }
}
''']
    bounds = {
        "float32": "return (w._code, float32(w._value))",
        "int32": "let (op, v) = w._bounds(-2147483648, 2147483647)\n    return (op, int32(v))",
        "uint32": "let (op, v) = w._bounds(0, 4294967295)\n    return (op, uint32(v))",
    }
    for t, zero, maxv, minv, add in TYPES:
        T = t[0].upper() + t[1:]
        out.append(f'''
@inlinable public func _test{T}(_ x: {t}, _ op: int32, _ v: {t}) -> bool {{
    if op == 0 {{ return x < v }}
    if op == 1 {{ return x <= v }}
    if op == 2 {{ return x > v }}
    if op == 3 {{ return x >= v }}
    if op == 4 {{ return x == v }}
    if op == 5 {{ return x != v }}
    return op == 6
}}

func _flag{T}(_ x: gpu.Span<{t}>, _ flags: gpu.MutableSpan<uint32>, _ op: int32, _ v: {t}) kernel {{
    let i = gpu.Index.x
    if i < x.count {{
        flags[i] = _test{T}(x[i], op, v) ? 1 : 0
    }}
}}

func _compact{T}(_ x: gpu.Span<{t}>, _ at: gpu.Span<uint32>, _ out: gpu.MutableSpan<{t}>, _ indices: gpu.MutableSpan<uint32>, _ op: int32, _ v: {t}, _ values: bool) kernel {{
    let i = gpu.Index.x
    if i < x.count && _test{T}(x[i], op, v) {{
        if values {{
            out[int(at[i])] = x[i]
        }} else {{
            indices[int(at[i])] = uint32(i)
        }}
    }}
}}

/// _op{T} is w as an operator and a value of {t}.
func _op{T}(_ w: Where) -> (int32, {t}) {{
    {bounds[t]}
}}

/// _where{T} is where each kept element of b goes, and how many there are.
func _where{T}(_ b: gpu.Buffer<{t}>, _ w: Where) async throws -> (gpu.Buffer<uint32>, int) {{
    let flags = try await b.Device.CreateBuffer(of: uint32.self, count: b.count)
    let (op, v) = _op{T}(w)
    try await _flag{T}.Launch(b, flags, op, v, over: b.count)
    let kept = int(try await Reduce(flags, .Sum))
    try await Scan(flags, exclusive: true)
    return (flags, kept)
}}

/// Count is how many elements of b satisfy w.
public func Count(_ b: gpu.Buffer<{t}>, where w: Where) async throws -> int {{
    if b.count == 0 {{ return 0 }}
    let flags = try await b.Device.CreateBuffer(of: uint32.self, count: b.count)
    let (op, v) = _op{T}(w)
    try await _flag{T}.Launch(b, flags, op, v, over: b.count)
    return int(try await Reduce(flags, .Sum))
}}

/// Select is the elements of b that satisfy w, in their order in b.
public func Select(_ b: gpu.Buffer<{t}>, where w: Where) async throws -> gpu.Buffer<{t}> {{
    if b.count == 0 {{ return try await b.Device.CreateBuffer(of: {t}.self, count: 0) }}
    let (at, kept) = try await _where{T}(b, w)
    let out = try await b.Device.CreateBuffer(of: {t}.self, count: kept)
    if kept > 0 {{
        let (op, v) = _op{T}(w)
        try await _compact{T}.Launch(b, at, out, at, op, v, true, over: b.count)
    }}
    return out
}}

/// SelectIndices is where in b the elements that satisfy w are, in
/// ascending order.
public func SelectIndices(_ b: gpu.Buffer<{t}>, where w: Where) async throws -> gpu.Buffer<uint32> {{
    if b.count == 0 {{ return try await b.Device.CreateBuffer(of: uint32.self, count: 0) }}
    let (at, kept) = try await _where{T}(b, w)
    let out = try await b.Device.CreateBuffer(of: uint32.self, count: kept)
    if kept > 0 {{
        let (op, v) = _op{T}(w)
        try await _compact{T}.Launch(b, at, b, out, op, v, false, over: b.count)
    }}
    return out
}}
''')
    return "".join(out)


def gather():
    out = [HEADER, '''//
// Gather, Scatter and ScatterAdd: moving elements by an index buffer.
// An index out of range traps, as every span access does.
import "gpu"
''']
    for t, zero, maxv, minv, add in TYPES:
        T = t[0].upper() + t[1:]
        out.append(f'''
func _gather{T}(_ src: gpu.Span<{t}>, _ indices: gpu.Span<uint32>, _ out: gpu.MutableSpan<{t}>) kernel {{
    let i = gpu.Index.x
    if i < indices.count {{
        out[i] = src[int(indices[i])]
    }}
}}

func _scatter{T}(_ src: gpu.Span<{t}>, _ indices: gpu.Span<uint32>, _ dst: gpu.MutableSpan<{t}>) kernel {{
    let i = gpu.Index.x
    if i < indices.count {{
        dst[int(indices[i])] = src[i]
    }}
}}

func _scatterAdd{T}(_ src: gpu.Span<{t}>, _ indices: gpu.Span<uint32>, _ dst: gpu.MutableSpan<{t}>) kernel {{
    let i = gpu.Index.x
    if i < indices.count {{
        _ = gpu.Atomic.Add(dst.Address(int(indices[i])), src[i])
    }}
}}

/// Gather is src at each of indices: out[i] = src[indices[i]].
public func Gather(_ src: gpu.Buffer<{t}>, _ indices: gpu.Buffer<uint32>) async throws -> gpu.Buffer<{t}> {{
    let out = try await src.Device.CreateBuffer(of: {t}.self, count: indices.count)
    if indices.count > 0 {{
        try await _gather{T}.Launch(src, indices, out, over: indices.count)
    }}
    return out
}}

/// Scatter writes each element of src to dst at its index: dst[indices[i]]
/// = src[i]. Where two indices are the same, which write lands is not
/// defined.
public func Scatter(_ src: gpu.Buffer<{t}>, _ indices: gpu.Buffer<uint32>, into dst: gpu.Buffer<{t}>) async throws {{
    if indices.count > 0 {{
        try await _scatter{T}.Launch(src, indices, dst, over: indices.count)
    }}
}}

/// ScatterAdd adds each element of src into dst at its index, atomically:
/// dst[indices[i]] += src[i]. An integer sum is exact whatever the order; a
/// float32 one is not deterministic, as the order of the additions is not.
public func ScatterAdd(_ src: gpu.Buffer<{t}>, _ indices: gpu.Buffer<uint32>, into dst: gpu.Buffer<{t}>) async throws {{
    if indices.count > 0 {{
        try await _scatterAdd{T}.Launch(src, indices, dst, over: indices.count)
    }}
}}
''')
    return "".join(out)


def main():
    for name, text in [("group", group()), ("reduce", reduce()), ("scan", scan()),
                       ("select", select()), ("gather", gather())]:
        with open(f"parallel/{name}.vs", "w") as f:
            f.write(text)


if __name__ == "__main__":
    main()
